name = "discovery-agent"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"

[[kv_namespaces]]
binding = "SESSION_KV"
id = "d7bfb3829df04578aa77a967e984f590"

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "a871481c4d5a4c789d2a48879cf3ca9c"
